---
# Task to install and configure Apache on Ubuntu

- name: Install Apache on Ubuntu
  ansible.builtin.package:
    name: apache2
    state: present

  ansible.builtin.copy:
    src: templates/index.html.j2
    dest: /var/www/html/index.html

  # Notify the 'Restart Apache' handler
  notify: Restart Apache
